### ISSUE TITLE
Секция Контента

### ISSUE THREAD

**Issue by foxhable** [aaccent/vpo-ex-pro_layout#5]
<details><summary>Скрин заголовка</summary>

![Image](https://github.com/aaccent/vpo-ex-pro_layout/assets/36298346/e705c725-3178-40ca-b390-1cc59ba3c23d)
</details> 

Эти странные заголовки думаю сделать так:

```html
<div class="content">
  <div class="content__title">
    <span>О компании</span>
    <h2>Тут нужно прописать главные тезисы о компании. Два-три предложения, чтобы не сломать дизайн-концепцию и нестандартную верстку текста</h2>
  </div>
  <p>Жирмунский, однако, настаивал, что синхрония доступна. Анжамбеман...</p>
</div>
```

Если заголовка нет, как здесь
<details><summary>Без заголовка</summary>

![Image](https://github.com/aaccent/vpo-ex-pro_layout/assets/36298346/a899c6f1-5a36-43dd-9ff7-cf097f632cb0)
</details> 

то можно сделать такое:
```scss
.content__title {
  margin-bottom: 36px;

  &:not(:has( :is(h2, h3, h4, h5, h6))) {
    margin-bottom: -100%;
  }
}
```

Все фотографии в контенте имеют анимацию, описанную на скрине

<details><summary>Скрин с описанием анимации</summary>

![Image](https://github.com/aaccent/vpo-ex-pro_layout/assets/36298346/653be10f-988a-415e-907f-333d3ed27e14)
</details>
